sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: luotovo
    password: Lt586826@
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tM5kmuXk7Qf6WziC39B
    access-key-secret: yVklvQTGFvVSBHWjqeHicuw9TZHe3K
    bucket-name: java-luot
  redis:
    host: localhost
    port: 6379
    database: 0
  wechat:
    appid: wxd2e9173d494c308f
    secret: f5181e1582ba9919250ea9fedc9caddc
    mchid:
    mcSerialNo:
    private-key-file-path:
    api-v3-key:
    we-chat-pay-cert-file-path:
    notify-url:
    refund-notify-url:
